# Generated by Django 3.1.7 on 2021-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unitname', models.CharField(max_length=56)),
                ('Allbeds', models.CharField(max_length=56)),
                ('Freebeds', models.CharField(max_length=56)),
                ('Occoupedbeds', models.CharField(max_length=56)),
                ('Impedingbeds', models.CharField(max_length=56)),
            ],
        ),
    ]
