# Generated by Django 3.1.7 on 2021-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalm',
            name='Freebeds',
        ),
        migrations.RemoveField(
            model_name='hospitalm',
            name='Occoupedbeds',
        ),
        migrations.AddField(
            model_name='hospitalm',
            name='Occupiedbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalm',
            name='Allbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalm',
            name='Impedingbeds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
